# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Scalingo API
email: hello@scalingo.com
description: Scalingo API
baseurl: ""
url: "https://developers.scalingo.com"
twitter_username: ScalingoHQ
github_username:  Scalingo

permalink: none
markdown: Rows
hard_wrap: false
input: GFM
syntax_highlighter: rouge

plugins:
  - jekyll-feed


collections:
  scalingo_api:
    output: true
    permalink: /:path
    title: "API V1"
  addon_provider_api:
    output: true
    permalink: /addon-provider-api/:path
    title: "Addon Provider API"
  one_click:
    output: true
    permalink: /one-click/:path
    title: "One-click Deployment API"
  scalingo_json_schema:
    output: true
    permalink: /scalingo-json-schema/:path
    title: "scalingo.json Schema"


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ld_library_path/

